[plugin]
id = "mysql-compiler-plugin"
class = "io.ballerina.stdlib.mysql.compiler.MySQLCompilerPlugin"

[[dependency]]
path = "../compiler-plugin/build/libs/mysql-compiler-plugin-1.11.1-SNAPSHOT.jar"
